services:
  my-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "demo"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      my-postgres:
        condition: service_healthy
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    command: sh -c "sleep 30 && java -jar /app/app.jar"

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
